// <auto-generated />
using System;
using CasaDiAna.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasaDiAna.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasaDiAna.Domain.Entities.CategoriaIngrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categorias_ingrediente", "estoque");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.CategoriaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categorias_produto", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.EntradaMercadoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_entrada");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("NumeroNotaFiscal")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("numero_nota_fiscal");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DataEntrada");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("NumeroNotaFiscal")
                        .HasFilter("numero_nota_fiscal IS NOT NULL");

                    b.ToTable("entradas_mercadoria", "estoque");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character(14)")
                        .HasColumnName("cnpj")
                        .IsFixedLength();

                    b.Property<string>("ContatoNome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contato_nome");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("RazaoSocial");

                    b.ToTable("fornecedores", "estoque", t =>
                        {
                            t.HasCheckConstraint("chk_cnpj_formato", "cnpj IS NULL OR cnpj ~ '^[0-9]{14}$'");
                        });
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.HistoricoImpressaoEtiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataProducao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_producao");

                    b.Property<DateTime>("ImpressoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("impresso_em");

                    b.Property<Guid>("ImpressoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("impresso_por");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("TipoEtiqueta")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_etiqueta");

                    b.HasKey("Id");

                    b.HasIndex("ImpressoEm")
                        .HasDatabaseName("ix_historico_impressao_etiquetas_impresso_em");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_historico_impressao_etiquetas_produto_id");

                    b.ToTable("historico_impressao_etiquetas", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ImportacaoVendas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_conteudo");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("PeriodoAte")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("periodo_ate");

                    b.Property<string>("PeriodoDe")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("periodo_de");

                    b.Property<int>("TotalIgnoradas")
                        .HasColumnType("integer")
                        .HasColumnName("total_ignoradas");

                    b.Property<int>("TotalImportadas")
                        .HasColumnType("integer")
                        .HasColumnName("total_importadas");

                    b.Property<int>("TotalLinhasParseadas")
                        .HasColumnType("integer")
                        .HasColumnName("total_linhas_parseadas");

                    b.Property<int>("TotalNaoEncontradas")
                        .HasColumnType("integer")
                        .HasColumnName("total_nao_encontradas");

                    b.HasKey("Id");

                    b.HasIndex("HashConteudo")
                        .IsUnique();

                    b.ToTable("importacoes_vendas", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo_interno");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<decimal?>("CustoUnitario")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("custo_unitario");

                    b.Property<decimal>("EstoqueAtual")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("estoque_atual");

                    b.Property<decimal?>("EstoqueMaximo")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("estoque_maximo");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<short>("UnidadeMedidaId")
                        .HasColumnType("smallint")
                        .HasColumnName("unidade_medida_id");

                    b.HasKey("Id");

                    b.HasIndex("CodigoInterno")
                        .IsUnique()
                        .HasFilter("codigo_interno IS NOT NULL");

                    b.HasIndex("UnidadeMedidaId");

                    b.HasIndex("CategoriaId", "Nome");

                    b.HasIndex("EstoqueAtual", "EstoqueMinimo")
                        .HasFilter("ativo = TRUE");

                    b.ToTable("ingredientes", "estoque", t =>
                        {
                            t.HasCheckConstraint("chk_estoque_atual_nao_negativo", "estoque_atual >= 0");

                            t.HasCheckConstraint("chk_estoque_minimo_nao_negativo", "estoque_minimo >= 0");
                        });
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_realizacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DataRealizacao");

                    b.HasIndex("Status");

                    b.ToTable("inventarios", "estoque");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ItemEntradaMercadoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("custo_unitario");

                    b.Property<Guid>("EntradaId")
                        .HasColumnType("uuid")
                        .HasColumnName("entrada_id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("EntradaId", "IngredienteId")
                        .IsUnique();

                    b.ToTable("itens_entrada_mercadoria", "estoque", t =>
                        {
                            t.HasCheckConstraint("chk_item_custo_nao_negativo", "custo_unitario >= 0");

                            t.HasCheckConstraint("chk_item_quantidade_positiva", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ItemFichaTecnica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadePorUnidade")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade_por_unidade");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("ProdutoId", "IngredienteId")
                        .IsUnique();

                    b.ToTable("itens_ficha_tecnica", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ItemInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<Guid>("InventarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventario_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("QuantidadeContada")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade_contada");

                    b.Property<decimal>("QuantidadeSistema")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade_sistema");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("InventarioId", "IngredienteId")
                        .IsUnique();

                    b.ToTable("itens_inventario", "estoque", t =>
                        {
                            t.HasCheckConstraint("chk_qtd_contada_nao_negativa", "quantidade_contada >= 0");

                            t.HasCheckConstraint("chk_qtd_sistema_nao_negativa", "quantidade_sistema >= 0");
                        });
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ModeloEtiquetaNutricional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AcucaresAdicionados")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("acucares_adicionados");

                    b.Property<decimal>("AcucaresTotais")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("acucares_totais");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<decimal>("Carboidratos")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carboidratos");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("FibraAlimentar")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fibra_alimentar");

                    b.Property<decimal>("GordurasSaturadas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gorduras_saturadas");

                    b.Property<decimal>("GordurasTotais")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gorduras_totais");

                    b.Property<decimal>("GordurasTrans")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gorduras_trans");

                    b.Property<string>("MedidaCaseira")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("medida_caseira");

                    b.Property<string>("Porcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("porcao");

                    b.Property<int?>("PorcoesPorEmbalagem")
                        .HasColumnType("integer")
                        .HasColumnName("porcoes_por_embalagem");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Proteinas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("proteinas");

                    b.Property<decimal>("Sodio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sodio");

                    b.Property<decimal>("ValorEnergeticoKJ")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_energetico_kj");

                    b.Property<decimal>("ValorEnergeticoKcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_energetico_kcal");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ix_modelos_etiqueta_nutricional_produto_id");

                    b.ToTable("modelos_etiqueta_nutricional", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referencia_tipo");

                    b.Property<decimal>("SaldoApos")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("saldo_apos");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("Tipo");

                    b.HasIndex("ReferenciaTipo", "ReferenciaId")
                        .HasFilter("referencia_id IS NOT NULL");

                    b.ToTable("movimentacoes", "estoque", t =>
                        {
                            t.HasCheckConstraint("chk_mov_quantidade_positiva", "quantidade > 0");

                            t.HasCheckConstraint("chk_mov_saldo_nao_negativo", "saldo_apos >= 0");
                        });
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.NotificacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_criacao");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingrediente_id");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean")
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mensagem");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("ix_notificacoes_estoque_data_criacao");

                    b.HasIndex("IngredienteId", "Lida")
                        .HasDatabaseName("ix_notificacoes_estoque_ingrediente_lida");

                    b.ToTable("notificacoes_estoque", "estoque");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.PerdaProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justificativa");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("ProdutoId", "Data");

                    b.ToTable("perdas_produto", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ProducaoDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<decimal>("CustoTotal")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("custo_total");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadeProduzida")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade_produzida");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("ProdutoId", "Data");

                    b.ToTable("producoes_diarias", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("AtualizadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("atualizado_por");

                    b.Property<Guid?>("CategoriaProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_produto_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("preco_venda");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaProdutoId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("produtos", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.UnidadeMedida", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("unidades_medida", "estoque");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Codigo = "KG",
                            Descricao = "Quilograma"
                        },
                        new
                        {
                            Id = (short)2,
                            Codigo = "G",
                            Descricao = "Grama"
                        },
                        new
                        {
                            Id = (short)3,
                            Codigo = "L",
                            Descricao = "Litro"
                        },
                        new
                        {
                            Id = (short)4,
                            Codigo = "ML",
                            Descricao = "Mililitro"
                        },
                        new
                        {
                            Id = (short)5,
                            Codigo = "UN",
                            Descricao = "Unidade"
                        },
                        new
                        {
                            Id = (short)6,
                            Codigo = "CX",
                            Descricao = "Caixa"
                        },
                        new
                        {
                            Id = (short)7,
                            Codigo = "PCT",
                            Descricao = "Pacote"
                        },
                        new
                        {
                            Id = (short)8,
                            Codigo = "DZ",
                            Descricao = "Dúzia"
                        });
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CodigoOtpExpiraEm")
                        .HasColumnType("timestamptz")
                        .HasColumnName("codigo_otp_expira_em");

                    b.Property<string>("CodigoOtpHash")
                        .HasColumnType("text")
                        .HasColumnName("codigo_otp_hash");

                    b.Property<int>("CodigoOtpTentativas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("codigo_otp_tentativas");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<bool>("TwoFactorHabilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_habilitado");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", "auth");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.VendaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("QuantidadeVendida")
                        .HasPrecision(15, 4)
                        .HasColumnType("numeric(15,4)")
                        .HasColumnName("quantidade_vendida");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("ProdutoId", "Data");

                    b.ToTable("vendas_diarias", "producao");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.EntradaMercadoria", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.HistoricoImpressaoEtiqueta", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Ingrediente", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.CategoriaIngrediente", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CasaDiAna.Domain.Entities.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ItemEntradaMercadoria", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.EntradaMercadoria", null)
                        .WithMany("Itens")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaDiAna.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ItemFichaTecnica", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaDiAna.Domain.Entities.Produto", null)
                        .WithMany("ItensFicha")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ItemInventario", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaDiAna.Domain.Entities.Inventario", null)
                        .WithMany("Itens")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ModeloEtiquetaNutricional", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.NotificacaoEstoque", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.PerdaProduto", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.ProducaoDiaria", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Produto", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.CategoriaProduto", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaProdutoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.VendaDiaria", b =>
                {
                    b.HasOne("CasaDiAna.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.EntradaMercadoria", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Inventario", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CasaDiAna.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensFicha");
                });
#pragma warning restore 612, 618
        }
    }
}
